### ISSUE TITLE
Wake from Sleep-Black Display

### ISSUE THREAD

**Issue by Saad-LUMS** [tlefko/XPS13-9350-Catalina#2]
Hey @tlefko I wiped my Mojave install and fresh installed Catalina using your files.
Everything works great, trackpad, brightness, sound from speakers (combojack not working though). Combojack works using the installer from Maz-1, check the sound issue thread for anyone interested.
However wake from sleep both using lid and menu, results in black screen leading to need for hard reboot.

**Comment by tlefko** [comment]
@Saad-LUMS I'm so sorry for me it didn't happen, I'll dig around and get back to you

**Comment by Saad-LUMS** [comment]
Let me know if there's any progress and if I can be of any help. If it does not work, it's fine.
Catalina actually does seem snappier than Mojave for some reason and the bug from Mojave of long authentication that was plaguing me is also gone now. So, I'm happy!

**Comment by tlefko** [comment]
@Saad-LUMS I told you its so strange but its much, much faster

**Comment by tlefko** [comment]
@Saad-LUMS by the way did you encounter any other bugs? //was the guide easy to follow

**Comment by Saad-LUMS** [comment]
The guide was very easy. No bugs so far. Will keep you posted.
However, there are a couple of changes I would suggest.

1. You should add my finding from insanelymac regarding stock card and kernel panic in your guide as pre-install step (as I suggested in that thread, check it out).

2. You should mention that the files have to be placed inside newly created folders called EFI (since you don't say to install Clover which would create the folder itself) inside the EFI partitions both in the installer USB and SSD, otherwise the installer disk image and installed Catalina partition will not be detected and shown in Clover upon boot. I made this mistake!

**Comment by Saad-LUMS** [comment]
![20200229_113312](https://user-images.githubusercontent.com/26320083/77438031-b919a900-6dbb-11ea-9085-6e053c4c763d.jpg)
You can clearly see the com.apple.driver.Airport.brcmNIC in the fourth line at the top before restarting at the end.

**Comment by tlefko** [comment]
@Saad-LUMS updated readme

**Comment by Saad-LUMS** [comment]
Read it. Much simpler for newbies.

**Comment by Saad-LUMS** [comment]
Also, yes the solution to sleep-wake could be related to ID's. Is your XPS same as mine? If it is then it should for me too. Or perhaps the DSDTs are not fully compatible. i5 6200U, QHD+ Touch, Samsung PM951 256GB SSD, 8 GB Ram.

**Comment by tlefko** [comment]
Same model yep @Saad-Lums, I also have i7

**Comment by Saad-LUMS** [comment]
I just tried adjusting the brightness after waking from sleep using lid. The backlight goes up and down (grey level) but no image of the UI. 
Also, Syscl's files gave perfect support for sleep-wake in Mojave on this system (other issues notwithstanding). Might get a lead by looking them over.

**Comment by tlefko** [comment]
@Saad-LUMS I just spoke to another user who has no seem wake bugs oncesoever with this build. It's so unusual. I tried syscls patches for lidwake but to no avail. I also had sleep wake bugs on Mojave. I tried adjusting the framebuffer but no luck. He has the same GPU as us so I'm really not sure what's different other than his resolution.

**Comment by Saad-LUMS** [comment]
<img width="780" alt="Screen Shot 2020-03-25 at 1 07 51 PM" src="https://user-images.githubusercontent.com/26320083/77564786-a4134780-6e99-11ea-9187-abe6a4646120.png">

Could these settings I've set be doing something to prevent sleep from working? Really shouldn't have any effect on sleeping from the menu.

**Comment by Saad-LUMS** [comment]
Nothing doing. Tried with different power settings. Also, I recall the first thing I did after fresh installing Catalina was testing sleep with default settings. So, still a no go.

**Comment by Saad-LUMS** [comment]
Off topic but I just installed 10.15.3, 3 days back thinking it would stay for a while and just yesterday 10.15.4 got released. Now, there's the annoying notification  bubble on Settings app in the Dock triggering my OCD :D

**Comment by tlefko** [comment]
@Saad-LUMS I really want to solve this issue

**Comment by Saad-LUMS** [comment]
> He has the same GPU as us so I'm really not sure what's different other than his resolution.

Maybe the difference in CPU is to blame since I have an i5. Does the other person have an i7 like you?

**Comment by tlefko** [comment]
@Saad-LUMS he does, it's so so strange.

**Comment by Saad-LUMS** [comment]
So, something, somewhere is not playing nice with my i5. Not fully compatible. Maybe some DSDT/SSDT combination.

**Comment by Saad-LUMS** [comment]
Do you guys have HD 520 or some other igpu?

**Comment by tlefko** [comment]
@Saad-LUMS hd 520. ... I really am not sure

**Comment by tlefko** [comment]
But the bug is on mine as well it just didn't happen on the first boot @Saad-LUMS so it's not just you

**Comment by Saad-LUMS** [comment]
Also, I did not use Catalina Patcher app to make the USB installer. I just used it to download the image and used createinstallmedia command in terminal since I don't want the patches it will add to the installer. Kept it vanilla.

**Comment by tlefko** [comment]
@Saad-LUMS It is patched! I fixed the sleep wake bug. I am updating the build files with it now, but if here are the instructions for you to just modify your existing setup.

#1 Disable intelbacklight patch from the config boot arguments
#2 Go to Graphics, and check Inject Intel
#3 Patch Framebuffer to 0x193B0005
#4 Patch ig-platform-id to 0x193B0005


That's it! It works perfectly on my system now. Lidwake, no black screen at all

**Comment by Saad-LUMS** [comment]
@tlefko Did you delete your comment regarding the fix? I got an email for it. Can't find it here. Was it not fixed?
Anyway, I tried 3 steps, can't figure out how to patch framebuffer. With the 3 steps done, no fix as of yet.
1. Inject Intel was already checked.

2. Deleted Boot argument for backlight.
<img width="254" alt="Screen Shot 2020-03-27 at 12 43 23 PM" src="https://user-images.githubusercontent.com/26320083/77779220-90e2b200-7028-11ea-8086-2e13fe864507.png">

3. Changed ig-platform-id:
<img width="130" alt="Screen Shot 2020-03-27 at 12 44 34 PM" src="https://user-images.githubusercontent.com/26320083/77779320-b8397f00-7028-11ea-931c-ea285ceb564f.png">

Do I change the hex here for framebuffer patching and enable it? I tried, didn't work, disabled it.
<img width="958" alt="Screen Shot 2020-03-27 at 12 45 27 PM" src="https://user-images.githubusercontent.com/26320083/77779399-d8693e00-7028-11ea-9c2c-ea6cef9429e3.png">

I also tried inserting into fake ID for intel GFX but that made the 520 show 20 mb memory and the brightness and resolution did not work properly. The display also showed up as a projector, so that's not it.
<img width="229" alt="Screen Shot 2020-03-27 at 12 45 51 PM" src="https://user-images.githubusercontent.com/26320083/77779444-e61ec380-7028-11ea-9517-de8ea9c34d6b.png">

**Comment by tlefko** [comment]
@Saad-LUMS I deleted the email for the fix as it did not work lol. I really am completely stumped. I tried looking at syscl's stuff and at HWPenable and all sorts of stuff and can't find anything. Also I've noticed a weird thing where preformance is worse on battery when it's below 80 percent, I think it's related to the display. Have you noticed anything?

**Comment by Saad-LUMS** [comment]
In regards to performance, I had my machine repaired a year ago when it went up in smoke (the board) and ever since then, it's performance has been terrible, stuttery and laggy on battery, okay >80% but way worse as it get's lower (perfect when plugged in). The battery has also gone down in quality and needs to be replaced so that could also be a culprit in poor performance on battery. So, I don't think it can be compared to a stock machine.
However, performance on battery on MacOS has been much better than in Windows for me. There is a negligible difference between battery and plugged-in.

**Comment by tlefko** [comment]
@Saad-LUMS oh wow, well I guess that's not a good benchmark. Either way, the sleep wake thing is the biggest issue it is driving me insane. I think it has to do with USB issues

**Comment by tlefko** [comment]
@Saad-LUMS okay, I have a new clover config if you want to test it. Improves performance and improves the sleep wake issue. Basically, if you close the lid and try to open it right away it does work, but you're no longer stuck after a black screen. Just let the lid close for 15-20 seconds and reopen and press a key and it will work. no more need for a restart. this build also fixed eject usb on sleep. it's a solid upgrade if you want to try it. There seems to small graphical glitches though after wakeup..

**Comment by Saad-LUMS** [comment]
Sure, let me test it.

**Comment by tlefko** [comment]
@Saad-LUMS ill send you my clover files, just fix the serial etc before you actually use it

[untitled folder 2.zip](https://github.com/tlefko/XPS13-9350-Catalina/files/4397921/untitled.folder.2.zip)

this should really improve your performance, even with the board It should be a major improvement. let me know. the sleep wake works it is just super finicky

**Comment by Saad-LUMS** [comment]
No improvement on the sleep front. Leaving for 15-20 seconds still brings up a black screen and pressing keys makes notification/error sounds as before. Will need to use it a bit for performance review (I can hear the fan more now).

**Comment by tlefko** [comment]
@Saad-LUMS try this, when the lid is open. Press the power button when you see that black screen. It should go to a blank screen with no blacklight. Then close the lid and open and it and repeat. This should work.

**Comment by Saad-LUMS** [comment]
I've reverted back to the old, original files as I found that sometimes, the new files would get stuck at boot until it completely borked it and would boot to a black screen (most likely resuming from sleep).
The trick with the lid had no effect on the original files.
Also, I've noticed another issue with both files. Sleeping on battery, shuts down the machine, both using menu and lid, for some reason.
I'm okay without sleep though, as is not as useful as hibernation which does not work on hackintoshes anyway. I use Aerial screensaver, have set a custom key combo for it and use it to lock the laptop when I'm away whilst it's plugged in.

**Comment by tlefko** [comment]
@Saad-LUMS sorry to hear, I guess for now the best option is just disable sleep so we can still close the lid

**Comment by tlefko** [comment]
@Saad-LUMS Hey, just wanted to let you know I posted a help request on a couple forums for this bug so maybe they can help us sort it out, I'll keep you posted if you're interested

**Comment by Saad-LUMS** [comment]
@tlefko Yeah, let's hope for the best. Also, filed another bug. See new post.

**Comment by tlefko** [comment]
@Saad-LUMS Saw it, not sure if it's a bug. Would you mind testing your build with an apple watch if you have one?

**Comment by Saad-LUMS** [comment]
> Would you mind testing your build with an apple watch if you have one?

Don't own an Apple Watch. Sorry!

**Comment by tlefko** [comment]
@Saad-LUMS all good, here's a link to the sleep wake support thread, there's a moderator trying to help but I'm lost.

www.tonymacx86.com/threads/xps-9350-catalina-help.295069/page-1

**Comment by Saad-LUMS** [comment]
> [www.tonymacx86.com/threads/xps-9350-catalina-help.295069/page-1](http://www.tonymacx86.com/threads/xps-9350-catalina-help.295069/page-1)

I have an issue with tonymac since they blocked my account when I posted for help with the wifi related KP you saw in InsanelyMac as well, citing piracy!!! Hypocrites...

**Comment by tlefko** [comment]
@Saad-LUMS Wow that's wild, overkill --- I think the guy is really knowledgable -- I have no idea what he is saying unfortunately and can't get his suggestions to work (or I am not doing them properly) feel free to try to do what he is saying though, then you can upload your clover for everyone if it works!

**Comment by tlefko** [comment]
@Saad-LUMS by the way, I patched the EDID for our display (did nothing whatsoever)

**Comment by tlefko** [comment]
@Saad-LUMS, publishing a new build that improves sleep. still not 100 percent. but this is noticeably better. -- note make sure to disable hibernation mode. as stated before, you can patch display overrides if you would like and can attach those files
